# Generated by Django 5.2.1 on 2026-04-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_hot_sale_live'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_is_feat_94b8d5_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_hot_sal_9aa8cf_idx',
            old_name='catalog_pro_hot_sal_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='hot_sale_live',
            field=models.BooleanField(default=False, help_text='Show this product in the Hot Sale section on the landing page.'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='catalog.product'),
        ),
    ]
