services:
  docs:
    image: cover_house_local_docs
    container_name: cover_house_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cover_house:/app/cover_house:z
    ports:
      - '9000:9000'
    command: /start-docs
