volumes:
  cover_production_postgres_data: {}
  cover_production_postgres_data_backups: {}
  cover_production_django_media: {}
  cover_production_django_staticfiles: {}
  
  cover_production_redis_data: {}
  
networks:
  cover_house:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: cover_house_production_django
    volumes:
      - cover_production_django_media:/app/cover_house/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - cover_house
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cover_house_production_postgres
    volumes:
      - cover_production_postgres_data:/var/lib/postgresql/data
      - cover_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - cover_house
    ports:
      - 5333:5432
    restart: always

  redis:
    image: docker.io/redis:6
    
    volumes:
      - cover_production_redis_data:/data
    
    networks:
      - cover_house
    restart: always

  celeryworker:
    <<: *django
    image: cover_house_production_celeryworker
    command: /start-celeryworker
    networks:
      - cover_house
    restart: always

  celerybeat:
    <<: *django
    image: cover_house_production_celerybeat
    command: /start-celerybeat
    networks:
      - cover_house
    restart: always

  flower:
    <<: *django
    image: cover_house_production_flower
    command: /start-flower
    networks:
      - cover_house
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: cover_house_production_nginx
    depends_on:
      - django
    volumes:
      - cover_production_django_media:/app/media
    ports:
      - 8002:80
    networks:
      - cover_house
    restart: always
