volumes:
  estorepostgres_data: {}
  estorepostgres_data_backups: {}
  estoredjango_media: {}
  estoredjango_staticfiles: {}
  
  estoreredis_data: {}
  
networks:
  backend:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: backend_estoredjango
    volumes:
      - estoredjango_media:/app/backend/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - backend
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_estorepostgres
    volumes:
      - estorepostgres_data:/var/lib/postgresql/data
      - estorepostgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - backend
    restart: always

  redis:
    image: docker.io/redis:6
    
    volumes:
      - estoreredis_data:/data
    
    networks:
      - backend
    restart: always

  celeryworker:
    <<: *django
    image: backend_estoreceleryworker
    command: /start-celeryworker
    networks:
      - backend
    restart: always

  celerybeat:
    <<: *django
    image: backend_estorecelerybeat
    command: /start-celerybeat
    networks:
      - backend
    restart: always

  flower:
    <<: *django
    image: backend_estoreflower
    command: /start-flower
    networks:
      - backend
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: backend_estorenginx
    depends_on:
      - django
    volumes:
      - estoredjango_media:/app/media
    ports:
      - 9229:80
    networks:
      - backend
    restart: always
