volumes:
  nice_postgres_data: {}
  nice_postgres_data_backups: {}
  nice_django_media: {}
  nice_django_staticfiles: {}
  
  nice_redis_data: {}
  
networks:
  backend:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: backend_nice_django
    volumes:
      - nice_django_media:/app/backend/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - backend
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_nice_postgres
    volumes:
      - nice_postgres_data:/var/lib/postgresql/data
      - nice_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - backend
    restart: always

  redis:
    image: docker.io/redis:6
    
    volumes:
      - nice_redis_data:/data
    
    networks:
      - backend
    restart: always

  celeryworker:
    <<: *django
    image: backend_nice_celeryworker
    command: /start-celeryworker
    networks:
      - backend
    restart: always

  celerybeat:
    <<: *django
    image: backend_nice_celerybeat
    command: /start-celerybeat
    networks:
      - backend
    restart: always

  flower:
    <<: *django
    image: backend_nice_flower
    command: /start-flower
    networks:
      - backend
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: backend_nice_nginx
    depends_on:
      - django
    volumes:
      - nice_django_media:/app/media
    ports:
      - 9229:80
    networks:
      - backend
    restart: always
