# Generated by Django 5.2.1 on 2026-04-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_item_sku'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_orde_status_6f1f4d_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_orde_created_a32bb7_idx',
        ),
    ]
