# Generated by Django 5.2.1 on 2026-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='E-Store and Accessories', max_length=120)),
                ('store_tagline', models.CharField(blank=True, default='', max_length=200)),
                ('hero_eyebrow', models.CharField(blank=True, default='', max_length=120)),
                ('hero_title_top', models.CharField(default='Gear up your', max_length=120)),
                ('hero_title_highlight', models.CharField(default='everyday tech.', max_length=120)),
                ('hero_subtitle', models.TextField(blank=True, default='Premium covers, screen guards, fast chargers, audio gear and smart wearables — handpicked for the way you live.')),
                ('hero_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1592286927505-1def25115558?w=900&q=80')),
                ('hero_primary_cta_label', models.CharField(default='Shop Covers', max_length=60)),
                ('hero_primary_cta_href', models.CharField(default='/category/mobile-covers', max_length=200)),
                ('hero_secondary_cta_label', models.CharField(default='Browse all', max_length=60)),
                ('hero_secondary_cta_href', models.CharField(default='#categories', max_length=200)),
                ('hero_stats', models.JSONField(blank=True, default=list)),
                ('trust_badges', models.JSONField(blank=True, default=list)),
                ('address_line1', models.CharField(default='Naya Bazaar, Pokhara-8', max_length=200)),
                ('address_line2', models.CharField(default='Kaski, Gandaki, Nepal', max_length=200)),
                ('phone', models.CharField(default='+977 9846-XXXXXX', max_length=40)),
                ('phone_note', models.CharField(default='Call or WhatsApp anytime', max_length=120)),
                ('email', models.EmailField(default='hello@estore.com.np', max_length=254)),
                ('hours', models.CharField(default='Sun – Fri · 10:00 AM – 8:00 PM', max_length=120)),
                ('hours_note', models.CharField(default='Closed Saturdays', max_length=120)),
                ('map_embed_url', models.URLField(blank=True, default='https://www.openstreetmap.org/export/embed.html?bbox=83.96%2C28.20%2C84.00%2C28.23&layer=mapnik&marker=28.215%2C83.985')),
                ('map_directions_url', models.URLField(blank=True, default='https://www.google.com/maps/search/?api=1&query=Naya+Bazaar+Pokhara+Nepal')),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('footer_about', models.TextField(blank=True, default='Your trusted destination in Pokhara for premium mobile covers, screen protectors, chargers, audio gear and smart wearables. Genuine products, honest prices, and same-day delivery in-city.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
