# Generated by Django 5.2.1 on 2026-05-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_coversku_unique_cover_per_variant_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_sku_per_cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cases.casecategory'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cases.casecolor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'cover_sku', 'category', 'color'), name='unique_combo_per_cart'),
        ),
    ]
