# Generated by Django 5.2.1 on 2026-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('inventory', 'Inventory'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('salary', 'Salary'), ('marketing', 'Marketing'), ('transport', 'Transport'), ('supplies', 'Supplies'), ('other', 'Other')], default='other', max_length=20)),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline (cash)')], default='offline', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
