# Generated by Django 5.2.1 on 2026-04-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_date_17a2b2_idx',
            old_name='expenses_ex_date_8b1c19_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_fcaba7_idx',
            old_name='expenses_ex_categor_4cf78c_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_source_6c1766_idx',
            old_name='expenses_ex_source_70a342_idx',
        ),
    ]
