# Generated by Django 5.2.1 on 2026-05-17 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category name')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Case Category',
                'verbose_name_plural': 'Case Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Colour name')),
                ('hex_code', models.CharField(blank=True, max_length=7, verbose_name='Hex code')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Case Colour',
                'verbose_name_plural': 'Case Colours',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoverSku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True)),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKU code')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price (NPR)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price; if set, overrides base_price for display.', max_digits=10, null=True, verbose_name='Discount price (NPR)')),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('fitment_notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='cases.casecategory')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='cases.casecolor')),
                ('phone_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='phones.phonevariant')),
            ],
            options={
                'verbose_name': 'Cover SKU',
                'verbose_name_plural': 'Cover SKUs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='covers/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('cover_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.coversku')),
            ],
            options={
                'verbose_name': 'Cover Image',
                'verbose_name_plural': 'Cover Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coversku',
            index=models.Index(fields=['phone_variant'], name='cases_cover_phone_v_96ef2e_idx'),
        ),
        migrations.AddIndex(
            model_name='coversku',
            index=models.Index(fields=['sku_code'], name='cases_cover_sku_cod_8ccdd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='coversku',
            constraint=models.UniqueConstraint(fields=('title', 'phone_variant', 'color'), name='unique_cover_variant_color'),
        ),
        migrations.AddIndex(
            model_name='coverimage',
            index=models.Index(fields=['cover_sku', 'is_primary'], name='cases_cover_cover_s_d87e03_idx'),
        ),
    ]
