# Generated by Django 5.2.1 on 2026-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coversku',
            name='unique_cover_variant_color',
        ),
        migrations.RemoveField(
            model_name='coversku',
            name='color',
        ),
        migrations.AddField(
            model_name='coversku',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='skus', to='cases.casecolor'),
        ),
        migrations.AddConstraint(
            model_name='coversku',
            constraint=models.UniqueConstraint(fields=('title', 'phone_variant'), name='unique_cover_per_variant'),
        ),
    ]
