# Generated by Django 5.2.1 on 2026-05-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_sitesettings'),
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coversku',
            name='unique_cover_per_variant',
        ),
        migrations.RemoveIndex(
            model_name='coversku',
            name='cases_cover_phone_v_96ef2e_idx',
        ),
        migrations.RemoveField(
            model_name='coversku',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coversku',
            name='title',
        ),
        migrations.AddField(
            model_name='coversku',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='skus', to='cases.casecategory'),
        ),
        migrations.AlterField(
            model_name='coversku',
            name='phone_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cover', to='phones.phonevariant'),
        ),
    ]
