# Generated by Django 5.2.1 on 2026-05-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_coversku_unique_cover_per_variant_and_more'),
        ('phones', '0002_phonevariant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversku',
            name='phone_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covers', to='phones.phonevariant'),
        ),
    ]
