# Generated by Django 5.2.1 on 2026-05-17 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Brand name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Series name')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_set', to='phones.brand')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['brand', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Model name')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_models', to='phones.series')),
            ],
            options={
                'verbose_name': 'Phone Model',
                'verbose_name_plural': 'Phone Models',
                'ordering': ['series', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Variant name')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='phones.phonemodel')),
            ],
            options={
                'verbose_name': 'Phone Variant',
                'verbose_name_plural': 'Phone Variants',
                'ordering': ['phone_model', 'name'],
                'constraints': [models.UniqueConstraint(fields=('phone_model', 'name'), name='unique_variant_per_model')],
            },
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_series_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='phonemodel',
            constraint=models.UniqueConstraint(fields=('series', 'name'), name='unique_model_per_series'),
        ),
    ]
